dist: xenial
sudo: required
language: c
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - python3-docutils
      - python3-pip
install:
  - pip3 install pipenv
  - git clone --recursive https://github.com/stedolan/jq
  - cd jq &&
    cd docs && pipenv sync && cd .. &&
    autoreconf -vif &&
    ./configure --with-oniguruma=builtin --disable-maintainer-mode &&
    sudo env "PATH=$PATH" make install && cd ..
  - git clone https://github.com/varnishcache/varnish-cache.git
  - cd varnish-cache && ./autogen.sh && ./configure && make &&
    sudo make install && sudo ldconfig && cd ..
before_script:
  - ./autogen.sh
script:
  - ./configure && make CFLAGS="-Wall -Wextra -Werror" VERBOSE=1 distcheck
